// Code generated by go-bindata.
// sources:
// ../../assets/db/postgres/create.sql
// ../../assets/db/postgres/truncate.pgsql
// DO NOT EDIT!

package assets_db

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _dbPostgresCreateSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x7c\x90\xcd\x4e\xb4\x30\x14\x86\xf7\xbd\x8a\x93\x59\x7d\x5f\xe2\x1d\xb0\x62\xb4\x9a\xc6\x11\x26\xc0\x62\x66\x35\xa9\x70\xc0\xc6\xb6\x68\x7f\x12\x2f\xdf\xb4\x50\xa2\xc3\x20\x3b\xce\x73\xda\xf7\x79\x4b\xee\x2b\x9a\x37\x14\xe8\xa9\xa1\x45\xcd\xca\x02\xd8\x23\x14\x65\x03\xf4\xc4\xea\xa6\x86\x56\x38\xfc\x72\x19\x21\xe4\xa1\x2a\x8f\xd0\xe4\xfb\x03\x0d\x2b\x33\x76\x6f\x06\x79\x97\xdd\x86\xfd\x68\xbc\xda\x60\x3b\x6f\xd1\xec\x32\x92\xf2\x27\x3e\x4d\xe1\x1f\x01\xd0\xa2\x7d\xd7\x5c\xe1\x6c\x00\xc7\x8a\xbd\xe4\xd5\x19\x9e\xe9\xf9\x8e\x00\xf4\x5e\xca\x88\x03\x0c\x03\xfe\x3a\x7a\xb7\xfc\xa1\xe2\x42\xa6\xa3\x5e\x8b\x4f\x8f\xa0\x47\x07\xda\x4b\x49\xfe\x5f\xc7\x46\xd1\x98\x2a\x3a\x58\xbe\x3d\x7b\xaa\x69\xc5\xf2\xc3\x75\x76\x90\xbc\x04\x3f\x80\x14\x61\xb0\x47\x83\xba\x45\x3b\x77\x08\x7b\x56\xfa\x21\x5d\x16\xb7\x92\x41\x80\x4e\x38\x89\xb7\xe0\x5a\x6f\x7a\xe4\xe4\xb7\xa9\x15\x5b\x5c\x44\x07\x42\x3b\x1c\xd0\xfc\x94\x8a\xec\xb7\xfb\x5f\xe6\xad\x41\xee\xb0\x03\x27\x14\x5a\xc7\xd5\xc7\x52\x67\xa3\xc7\x6a\xac\xd0\x5a\x3e\xe0\xaa\xda\x77\x00\x00\x00\xff\xff\xe5\xdb\xc0\xba\x70\x02\x00\x00")

func dbPostgresCreateSqlBytes() ([]byte, error) {
	return bindataRead(
		_dbPostgresCreateSql,
		"db/postgres/create.sql",
	)
}

func dbPostgresCreateSql() (*asset, error) {
	bytes, err := dbPostgresCreateSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "db/postgres/create.sql", size: 624, mode: os.FileMode(436), modTime: time.Unix(1539894125, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _dbPostgresTruncatePgsql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x0a\x09\x0a\xf5\x73\x76\x0c\x71\x55\xf0\xf7\xf3\x89\x54\x50\x2a\x2d\x4e\x2d\x52\xd2\x51\x48\xcb\x2f\x2a\xcd\xd5\x51\x28\xc9\x28\x4a\x4d\x4c\xb1\x06\x04\x00\x00\xff\xff\x8d\x30\x9a\x58\x24\x00\x00\x00")

func dbPostgresTruncatePgsqlBytes() ([]byte, error) {
	return bindataRead(
		_dbPostgresTruncatePgsql,
		"db/postgres/truncate.pgsql",
	)
}

func dbPostgresTruncatePgsql() (*asset, error) {
	bytes, err := dbPostgresTruncatePgsqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "db/postgres/truncate.pgsql", size: 36, mode: os.FileMode(436), modTime: time.Unix(1539889865, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"db/postgres/create.sql": dbPostgresCreateSql,
	"db/postgres/truncate.pgsql": dbPostgresTruncatePgsql,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"db": &bintree{nil, map[string]*bintree{
		"postgres": &bintree{nil, map[string]*bintree{
			"create.sql": &bintree{dbPostgresCreateSql, map[string]*bintree{}},
			"truncate.pgsql": &bintree{dbPostgresTruncatePgsql, map[string]*bintree{}},
		}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

